In [1]:
import pandas as pd
import numpy as np

pd.options.plotting.backend = "plotly"

In [2]:
df_car = pd.read_csv("dataset_car.csv")
df_car.head()

,car name,cylinders,displacement,horsepower,weight,acceleration,model year,origin,mpg
0,chevrolet chevelle malibu,8.0,307.0,130,3504.0,12.0,70.0,1.0,18.0
1,buick skylark 320,8.0,350.0,165,3693.0,11.5,70.0,1.0,15.0
2,plymouth satellite,8.0,318.0,150,3436.0,11.0,70.0,1.0,18.0
3,amc rebel sst,8.0,304.0,150,3433.0,12.0,70.0,1.0,16.0
4,ford torino,8.0,302.0,140,3449.0,10.5,70.0,NaN,17.0

In [3]:
df_car.describe()

,cylinders,displacement,weight,acceleration,model year,origin,mpg
count,390.000000,391.000000,387.000000,391.000000,388.000000,390.000000,398.000000
mean,5.453846,193.937340,2965.614987,15.561893,76.028351,1.574359,23.514573
std,1.701858,104.405603,850.709335,2.758661,3.709994,0.803821,7.815984
min,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000,9.000000
25%,4.000000,104.500000,2220.000000,13.900000,73.000000,1.000000,17.500000
50%,4.000000,151.000000,2800.000000,15.500000,76.000000,1.000000,23.000000
75%,8.000000,262.000000,3589.500000,17.150000,79.000000,2.000000,29.000000
max,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000,46.600000

In [4]:
df_car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   car name      398 non-null    object
 1   cylinders     390 non-null    float64
 2   displacement  391 non-null    float64
 3   horsepower    395 non-null    object
 4   weight        387 non-null    float64
 5   acceleration  391 non-null    float64
 6   model year    388 non-null    float64
 7   origin        390 non-null    float64
 8   mpg           398 non-null    float64
dtypes: float64(7), object(2)
memory usage: 28.1+ KB

In [5]:
df_car["horsepower"].values

array(['130', '165', '150', '150', '140', '198', '220', '215', '225',
       '190', '170', '160', '150', '225', '95', '95', '97', '85', '88',
       '46', '87', '90', '95', '113', '90', '215', '200', '210', '193',
       '88', '90', '95', '?', '100', '105', '100', '88', '100', '165',
       '175', '153', '150', '180', '170', '175', '110', '72', '100', '88',
       '86', '90', '70', '76', '65', '69', '60', '70', '95', '80', '54',
       '90', '86', '165', '175', '150', '153', nan, '208', '155', '160',
       '190', '97', '150', '130', '140', '150', '112', '76', '87', '69',
       '86', '92', '97', '80', '88', '175', '150', '145', '137', '150',
       '198', '150', '158', '150', '215', '225', '175', '105', '100', nan,
       '88', '95', '46', '150', '167', '170', '180', '100', '88', '72',
       '94', '90', '85', '107', '90', '145', '230', '49', '75', '91',
       '112', '150', '110', '122', '180', '95', '?', '100', '100', '67',
       '80', '65', '75', '100', '110', '105', '140', '150', '150', '140',
       '150', '83', '67', '78', '52', '61', '75', '75', '75', '97', '93',
       '67', '95', '105', '72', '72', '170', '145', '150', '148', '110',
       '105', '110', '95', '110', '110', '129', '75', '83', '100', '78',
       '96', '71', '97', '97', '70', '90', '95', '88', '98', '115', '53',
       '86', '81', '92', '79', '83', '140', '150', '120', '152', '100',
       '105', '81', '90', '52', '60', '70', '53', '100', '78', '110',
       '95', '71', '70', '75', '72', '102', '150', '88', '108', '120',
       '180', '145', '130', '150', '68', '80', '58', '96', '70', '145',
       '110', '145', '130', '110', '105', '100', '98', '180', '170',
       '190', '149', '78', '88', '75', '89', '63', '83', '67', '78', '97',
       '110', '110', '48', '66', '52', '70', '60', '110', '140', '139',
       '105', '95', '85', '88', '100', '90', '105', '85', '110', '120',
       '145', '165', '139', '140', '68', '95', '97', '75', '95', '105',
       '85', '97', '103', '125', '115', '133', '71', '68', '115', '85',
       '88', '90', '110', '130', '129', '138', '135', '155', '142', '125',
       '150', '71', '65', '80', '80', '77', '125', '71', '90', '70', '70',
       '65', '69', '90', '115', '115', '90', '76', '60', '70', '65', nan,
       '88', '90', '90', '78', '90', '75', '92', '75', '65', '105', '65',
       '48', '48', '67', '67', '67', '?', '67', '62', '132', '100', '88',
       '?', '72', '84', '84', '92', '110', '84', '58', '64', '60', '67',
       '65', '62', '68', '63', '65', '65', '74', '?', '75', '75', '100',
       '74', '80', '76', '116', '120', '110', '105', '88', '85', '88',
       '88', '88', '85', '84', '90', '92', '?', '74', '68', '68', '63',
       '70', '88', '75', '70', '67', '67', '67', '110', '85', '92', '112',
       '96', '84', '90', '86', '52', '84', '79', '82'], dtype=object)

In [6]:
df_car[df_car['horsepower'].str.isnumeric() != True] #important, si on met == False

,car name,cylinders,displacement,horsepower,weight,acceleration,model year,origin,mpg
32,ford pinto,4.0,98.0,?,2046.0,19.0,71.0,1.0,25.0
66,amc ambassador sst,8.0,304.0,NaN,3672.0,11.5,72.0,1.0,17.0
99,amc hornet,6.0,232.0,NaN,2945.0,16.0,73.0,1.0,18.0
126,ford maverick,6.0,200.0,?,2875.0,17.0,74.0,1.0,21.0
313,chevrolet citation,4.0,151.0,NaN,2678.0,16.5,80.0,1.0,28.0
330,renault lecar deluxe,4.0,85.0,?,1835.0,17.3,80.0,2.0,40.9
336,ford mustang cobra,4.0,140.0,?,2905.0,14.3,80.0,1.0,23.6
354,renault 18i,4.0,100.0,?,2320.0,15.8,81.0,2.0,34.5
374,amc concord dl,4.0,151.0,?,3035.0,20.5,82.0,1.0,23.0

In [7]:
df_car=df_car.replace('?',np.nan)
df_car[df_car['horsepower'].str.isnumeric() != True]

,car name,cylinders,displacement,horsepower,weight,acceleration,model year,origin,mpg
32,ford pinto,4.0,98.0,NaN,2046.0,19.0,71.0,1.0,25.0
66,amc ambassador sst,8.0,304.0,NaN,3672.0,11.5,72.0,1.0,17.0
99,amc hornet,6.0,232.0,NaN,2945.0,16.0,73.0,1.0,18.0
126,ford maverick,6.0,200.0,NaN,2875.0,17.0,74.0,1.0,21.0
313,chevrolet citation,4.0,151.0,NaN,2678.0,16.5,80.0,1.0,28.0
330,renault lecar deluxe,4.0,85.0,NaN,1835.0,17.3,80.0,2.0,40.9
336,ford mustang cobra,4.0,140.0,NaN,2905.0,14.3,80.0,1.0,23.6
354,renault 18i,4.0,100.0,NaN,2320.0,15.8,81.0,2.0,34.5
374,amc concord dl,4.0,151.0,NaN,3035.0,20.5,82.0,1.0,23.0

In [14]:
df_car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   car name      398 non-null    object
 1   cylinders     390 non-null    float64
 2   displacement  391 non-null    float64
 3   horsepower    389 non-null    object
 4   weight        387 non-null    float64
 5   acceleration  391 non-null    float64
 6   model year    388 non-null    float64
 7   origin        390 non-null    float64
 8   mpg           398 non-null    float64
dtypes: float64(7), object(2)
memory usage: 28.1+ KB

In [16]:
df_car['horsepower'] = df_car['horsepower'].astype(np.float64)

In [17]:
df_car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   car name      398 non-null    object
 1   cylinders     390 non-null    float64
 2   displacement  391 non-null    float64
 3   horsepower    389 non-null    float64
 4   weight        387 non-null    float64
 5   acceleration  391 non-null    float64
 6   model year    388 non-null    float64
 7   origin        390 non-null    float64
 8   mpg           398 non-null    float64
dtypes: float64(8), object(1)
memory usage: 28.1+ KB

In [18]:
df_car.isna().plot(kind='imshow')

In [19]:
X = df_car.drop(columns=['car name', 'mpg'])
y = df_car['mpg']

In [20]:
X.isna().plot(kind='imshow')

In [22]:
X.apply(lambda x: x.fillna(x.median()),axis=0).isna().plot(kind='imshow')

In [23]:
from sklearn.impute import SimpleImputer

median_imputer = SimpleImputer(strategy='median')
X_imputed_median = pd.DataFrame(
    median_imputer.fit_transform(X),
    columns=X.columns
)
X_imputed_median.isna().plot(kind='imshow')
X_imputed_median

,cylinders,displacement,horsepower,weight,acceleration,model year,origin
0,8.0,307.0,130.0,3504.0,12.0,70.0,1.0
1,8.0,350.0,165.0,3693.0,11.5,70.0,1.0
2,8.0,318.0,150.0,3436.0,11.0,70.0,1.0
3,8.0,304.0,150.0,3433.0,12.0,70.0,1.0
4,8.0,302.0,140.0,3449.0,10.5,70.0,1.0
...,...,...,...,...,...,...,...
393,4.0,140.0,86.0,2790.0,15.6,82.0,1.0
394,4.0,97.0,52.0,2130.0,24.6,82.0,2.0
395,4.0,135.0,84.0,2295.0,11.6,82.0,1.0
396,4.0,120.0,79.0,2625.0,18.6,82.0,1.0
397,4.0,119.0,82.0,2720.0,19.4,82.0,1.0

In [24]:
from sklearn.impute import KNNImputer

knn_imputer = KNNImputer(n_neighbors=5)
X_imputed_knn = pd.DataFrame(
    knn_imputer.fit_transform(X),
    columns=X.columns
)
X_imputed_knn.isna().plot(kind='imshow')
X_imputed_knn

,cylinders,displacement,horsepower,weight,acceleration,model year,origin
0,8.0,307.0,130.0,3504.0,12.0,70.0,1.0
1,8.0,350.0,165.0,3693.0,11.5,70.0,1.0
2,8.0,318.0,150.0,3436.0,11.0,70.0,1.0
3,8.0,304.0,150.0,3433.0,12.0,70.0,1.0
4,8.0,302.0,140.0,3449.0,10.5,70.0,1.0
...,...,...,...,...,...,...,...
393,4.0,140.0,86.0,2790.0,15.6,82.0,1.0
394,4.0,97.0,52.0,2130.0,24.6,82.0,2.0
395,4.0,135.0,84.0,2295.0,11.6,82.0,1.0
396,4.0,120.0,79.0,2625.0,18.6,82.0,1.0
397,4.0,119.0,82.0,2720.0,19.4,82.0,1.0

In [27]:
df = X_imputed_knn.join(y)

In [28]:
df.plot(kind='scatter', x='weight', y='mpg')

In [29]:
df.plot(kind='scatter', x='horsepower', y='mpg')

In [34]:
df.plot(kind='scatter', x='model year', y='mpg')