In [24]:
import pandas as pd
auto_mpg = pd.read_csv('auto-mpg.xls', sep = ',')
auto_mpg

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [25]:
df = auto_mpg[['car name', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'mpg']]

I'll randomly replace a small fraction of values (5%) in the dataframe with NaN to introduce some missing data.

In [26]:
import numpy as np

drop_frac = 0.02
df_with_nan = df.copy()

for col in df_with_nan.columns:
    if col != 'car name' and col != 'mpg':
        mask = np.random.rand(len(df_with_nan)) < drop_frac
        df_with_nan.loc[mask, col] = np.nan

df_with_nan

,car name,cylinders,displacement,horsepower,weight,acceleration,model year,origin,mpg
0,chevrolet chevelle malibu,8.0,307.0,130,3504.0,12.0,70.0,1.0,18.0
1,buick skylark 320,8.0,350.0,165,3693.0,11.5,70.0,1.0,15.0
2,plymouth satellite,8.0,318.0,150,3436.0,11.0,70.0,1.0,18.0
3,amc rebel sst,8.0,304.0,150,3433.0,12.0,70.0,1.0,16.0
4,ford torino,8.0,302.0,140,3449.0,10.5,70.0,NaN,17.0
...,...,...,...,...,...,...,...,...,...
393,ford mustang gl,4.0,140.0,86,2790.0,15.6,82.0,1.0,27.0
394,vw pickup,4.0,97.0,52,2130.0,24.6,82.0,2.0,44.0
395,dodge rampage,4.0,135.0,84,2295.0,11.6,82.0,1.0,32.0
396,ford ranger,4.0,120.0,79,2625.0,18.6,82.0,1.0,28.0
397,chevy s-10,4.0,119.0,82,2720.0,19.4,82.0,1.0,31.0

In [27]:
df_with_nan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   car name      398 non-null    object
 1   cylinders     390 non-null    float64
 2   displacement  391 non-null    float64
 3   horsepower    395 non-null    object
 4   weight        387 non-null    float64
 5   acceleration  391 non-null    float64
 6   model year    388 non-null    float64
 7   origin        390 non-null    float64
 8   mpg           398 non-null    float64
dtypes: float64(7), object(2)
memory usage: 28.1+ KB

In [30]:
df_with_nan.isna().sum()

car name         0
cylinders        8
displacement     7
horsepower       3
weight          11
acceleration     7
model year      10
origin           8
mpg              0
dtype: int64

In [28]:
df_with_nan.to_csv("dataset_car.csv", index=False)