In [1]:
import pandas as pd

pd.options.plotting.backend = "plotly"

In [2]:
df = pd.read_csv("dataset.csv")
df.head()

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,malignant
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,True
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,True
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,True
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,True
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,True

In [3]:
df.describe()

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,...,13.010000,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,...,18.790000,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

In [4]:
df.columns

Index(['radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean',
       'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'malignant'],
      dtype='object')

In [5]:
df.plot(kind='hist', x='texture_mean', color='malignant')

In [6]:
df.plot(kind='hist', x='texture_mean', color='malignant', barmode='overlay', histnorm='percent')

In [7]:
df.plot(kind='hist', x='smoothness_mean', color='malignant', barmode='overlay', histnorm='percent')

In [8]:
df.plot(kind='scatter', x='texture_mean', y='smoothness_mean', color='malignant')

In [9]:
X = df.drop(columns=['malignant'])
y = df['malignant']

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=12345, stratify=y) # stratification

In [11]:
y.value_counts(normalize=True), y_train.value_counts(normalize=True), y_test.value_counts(normalize=True)

(malignant
 False    0.627417
 True     0.372583
 Name: proportion, dtype: float64,
 malignant
 False    0.626374
 True     0.373626
 Name: proportion, dtype: float64,
 malignant
 False    0.631579
 True     0.368421
 Name: proportion, dtype: float64)

In [12]:
# Fusion de X_train et y_train
df_train = X_train.copy()
df_train['malignant'] = y_train

# Préparation de X_test avec '?' pour "malevolent"
df_test = X_test.copy()
df_test['malignant'] = '?'

# Concaténation finale
pd.concat([df_train, df_test], ignore_index=True).plot(kind='scatter', x='texture_mean', y='smoothness_mean', color='malignant')

In [13]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

KNeighborsClassifier()

In [14]:
sum(knn.predict(X_test) == y_test)/len(X_test) #knn.score(X_test, y_test)

0.9473684210526315

In [15]:
knn.score(X_test, y_test)

0.9473684210526315

In [16]:
scores = pd.DataFrame(data=[i for i in range(2, 300)], columns=['score'], index=range(2, 300))

scores['score'] = scores['score'].apply(lambda i: KNeighborsClassifier(n_neighbors=i).fit(X_train, y_train).score(X_test, y_test))
scores.plot()

In [17]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

cv_scores = cross_val_score(knn, X, y, cv=skf)

print("Scores CV:", cv_scores)
print("Score CV min:", cv_scores.min())

Scores CV: [0.92982456 0.90350877 0.92982456 0.95614035 0.95575221]
Score CV min: 0.9035087719298246

In [18]:
scores = pd.DataFrame(data=[i for i in range(2, 300)], columns=['score'], index=range(2, 300))

scores['score'] = scores['score'].apply(lambda i: cross_val_score(KNeighborsClassifier(n_neighbors=i), X, y, cv=skf).min())
scores.plot()

In [19]:
prediction = knn.predict(X_test)

VP = sum(prediction[y_test == True])
FN = sum(~prediction[y_test == True])
FP = sum(~y_test[prediction == True])

precision = VP/(VP + FP)
recall = VP/(VP + FN)
f1 = 2*precision*recall/(precision+recall)

precision, recall, f1

(np.float64(0.9736842105263158),
 np.float64(0.8809523809523809),
 np.float64(0.925))

In [20]:
from sklearn.metrics import precision_score, recall_score, f1_score

precision_score(y_test, prediction), recall_score(y_test, prediction), f1_score(y_test, prediction)

(0.9736842105263158, 0.8809523809523809, 0.925)

In [21]:
cv_scores = cross_val_score(knn, X, y, cv=skf, scoring='f1')

print("Scores CV:", cv_scores)
print("Score CV min:", cv_scores.min())

Scores CV: [0.90909091 0.86075949 0.90243902 0.94252874 0.93670886]
Score CV min: 0.8607594936708861

In [22]:
scores = pd.DataFrame(data=[i for i in range(2, 300)], columns=['score'], index=range(2, 300))

scores['score_acc'] = scores['score'].apply(lambda i: cross_val_score(KNeighborsClassifier(n_neighbors=i), X, y, cv=skf).min())
scores['score_f1'] = scores['score'].apply(lambda i: cross_val_score(KNeighborsClassifier(n_neighbors=i), X, y, cv=skf, scoring='f1').min())
scores[['score_acc', 'score_f1']].plot()

In [23]:
knn = KNeighborsClassifier(n_neighbors=17)

cross_val_score(knn, X, y, cv=skf, scoring='f1').min()

np.float64(0.875)

In [24]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, RobustScaler

pipe = Pipeline([
    ('scale', StandardScaler()),
    ('clf', knn)
    ])

cross_val_score(pipe, X, y, cv=skf, scoring='f1').min()

np.float64(0.8974358974358975)

In [25]:
from sklearn.preprocessing import RobustScaler

pipe = Pipeline([
    ('scale', RobustScaler()),
    ('clf', knn)
    ])

cross_val_score(pipe, X, y, cv=skf, scoring='f1').min()

np.float64(0.9113924050632911)

In [26]:
from sklearn.linear_model import LogisticRegression

lreg = LogisticRegression(random_state=0, max_iter=10_000, penalty=None).fit(X_train, y_train)

C:\Users\Concordance\PycharmProjects\ateliers-data-2025-2026\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning:

lbfgs failed to converge after 10000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=10000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression

In [27]:
lreg = LogisticRegression(random_state=0, max_iter=10_000, penalty=None, solver='saga').fit(X_train, y_train)

In [28]:
lreg.score(X_test, y_test), f1_score(y_test, lreg.predict(X_test)), cross_val_score(lreg, X, y, cv=skf, scoring='f1').min()

(0.9298245614035088, 0.9024390243902439, np.float64(0.8536585365853658))

In [29]:
from sklearn.preprocessing import RobustScaler

pipe = Pipeline([
    ('scale', RobustScaler()),
    ('clf', lreg)
    ])

cross_val_score(pipe, X, y, cv=skf, scoring='f1').min()

np.float64(0.926829268292683)

In [30]:
X.columns

Index(['radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean',
       'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [31]:
pipe.fit(X, y)

coef_df = pd.DataFrame({
    'feature': X.columns,
    'coefficient': pipe._final_estimator.coef_[0]
})
coef_df.plot(x='feature', y='coefficient', kind='bar')

In [32]:
lreg = LogisticRegression(random_state=0, max_iter=10_000, penalty='l2', solver='saga').fit(X_train, y_train)

pipe = Pipeline([
    ('scale', RobustScaler()),
    ('clf', lreg)
    ])

cross_val_score(pipe, X, y, cv=skf, scoring='f1').min()

np.float64(0.9382716049382716)

In [33]:
pipe.fit(X, y)

coef_df = pd.DataFrame({
    'feature': X.columns,
    'coefficient': pipe._final_estimator.coef_[0]
})
coef_df.plot(x='feature', y='coefficient', kind='bar')

In [34]:
coef_df_sorted = coef_df.reindex(coef_df['coefficient'].abs().sort_values(ascending=False).index)
coef_df_sorted.plot(x='feature', y='coefficient', kind='bar')

In [35]:
top_n_features = coef_df_sorted.head(15)["feature"].values
top_n_features

array(['texture_worst', 'area_se', 'area_worst', 'concave points_worst',
       'concavity_worst', 'symmetry_worst', 'concavity_mean',
       'radius_worst', 'concave points_mean', 'radius_se',
       'smoothness_worst', 'compactness_se', 'perimeter_worst',
       'fractal_dimension_se', 'texture_mean'], dtype=object)

In [36]:
cross_val_score(pipe, X, y, cv=skf, scoring='f1').min(), cross_val_score(pipe, X[top_n_features], y, cv=skf, scoring='f1').min()

(np.float64(0.9382716049382716), np.float64(0.975609756097561))

In [37]:
from sklearn.inspection import permutation_importance

pipe.fit(X_train, y_train)
result = permutation_importance(
    pipe, X_test, y_test, n_repeats=10, random_state=42, n_jobs=2
)

sorted_importances_idx = result.importances_mean.argsort()
importances = pd.DataFrame(
    result.importances[sorted_importances_idx].T,
    columns=X.columns[sorted_importances_idx],
)
importances.plot(kind='box')